In [32]:
import torch
import numpy as np

# Tensor Class

In [33]:
t = torch.Tensor()
type(t)

torch.Tensor

# Tensor attributes

In [34]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [35]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

### Tensor computations depend on the device and the type

In [36]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1.,2.,3.])

In [37]:
t1.dtype

torch.int64

In [38]:
t2.dtype

torch.float32

In [39]:
t1 + t2

tensor([2., 4., 6.])

In [40]:
t2 = t1.cuda()

In [41]:
t1.device

device(type='cpu')

In [42]:
t2.device

device(type='cuda', index=0)

In [ ]:
t1 + t2

# Creation options using data

In [ ]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [44]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [45]:
torch.tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [46]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [47]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

# Creation options without data

In [48]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [49]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [50]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [51]:
torch.rand(2,2)

tensor([[0.8631, 0.6772],
        [0.4822, 0.5119]])

# Creating PyTorch Tensors - Best Options

In [52]:
data = np.array([1,2,3])

In [53]:
t1 = torch.Tensor(data) # Class Constructor Function
t2 = torch.tensor(data) # Factories Function
t3 = torch.as_tensor(data) # Factories Function
t4 = torch.from_numpy(data) # Factories Function

In [54]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [55]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [56]:
torch.get_default_dtype()

torch.float32

In [58]:
torch.tensor(np.array([1,2,3]))

tensor([1, 2, 3], dtype=torch.int32)

In [59]:
torch.tensor(np.array([1.,2.,3.]))

tensor([1., 2., 3.], dtype=torch.float64)

In [61]:
torch.tensor(np.array([1,2,3]), dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

## Memory: Sharing vs Copying

In [63]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [64]:
t1 = torch.Tensor(data) 
t2 = torch.tensor(data)
t3 = torch.as_tensor(data) 
t4 = torch.from_numpy(data)

In [65]:
data[0] = 0
data[1] = 0
data[2] = 0

In [66]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


In [67]:
print(t3)
print(t4)

tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)


### Best Option: 
Normal Use torch.tensor

Use torch.as_tensor To Get High Performance

torch.from_numpy Only Accept Numpy Array